version: '2'
volumes:
    config:
    mosquitto:
    zigbee2mqtt:
services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    network_mode: host
    volumes:
      - config:/config
    labels:
      io.balena.features.dbus: "1"
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: unix:path=/host/run/dbus/system_bus_socket
    privileged: true

  mqtt:
    build: mqtt
    ports:
      - "1883:1883"
    restart: always
    volumes:
      - mosquitto:/mosquitto/data
    tmpfs:
      - /mosquitto/log

  # https://www.zigbee2mqtt.io/guide/getting-started/#installation
  zigbee2mqtt:
    build: zigbee2mqtt
    volumes:
      - zigbee2mqtt:/app/data
    ports:
      - 7000:7000
      # - 8080:8080
    devices: 
      - /dev/ttyUSB0:/dev/ttyACM0
    privileged: true

  # hass-configurator:
  #   image: "causticlab/hass-configurator-docker:latest"
  #   restart: always
  #   ports:
  #     - "3218:3218"
  #   volumes:
  #     - 'config:/hass-config'
  #   environment:
  #     - HC_BASEPATH=/hass-config
