version: '2'
volumes:
    config:
    mosquitto:
    zigbee2mqtt:
services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    network_mode: host
    volumes:
      - config:/config
    labels:
      io.balena.features.dbus: "1"
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: unix:path=/host/run/dbus/system_bus_socket
    privileged: true

  mqtt:
    build: mqtt
    ports:
      - "1883:1883"
    volumes:
      - mosquitto:/mosquitto/data
    tmpfs:
      - /mosquitto/log

  # https://www.zigbee2mqtt.io/guide/getting-started/#installation
  zigbee2mqtt:
    build: zigbee2mqtt
    volumes:
      - zigbee2mqtt:/app/data
    ports:
      - 7000:7000
      # - 8080:8080
    devices: 
      - /dev/ttyUSB0:/dev/ttyACM0
    privileged: true

  code-server:
    image: codercom/code-server:4.91.1@sha256:8403442d3472e411f72b6a5267b5ee0e62db27e258d81efebef40c3b41219970
    command:
      - --port=9000
      - --auth=none
      - --extensions-dir=/config/.vscode
      - --user-data-dir=/config/.vscode
      - /config
    working_dir: /config
    ports:
      - 9000:9000/tcp
    volumes:
      - config:/config
      - zigbee2mqtt:/config/zigbee2mqtt
      # - esphome:/config/esphome
      # - frigate-config:/config/frigate
    user: root

 # https://github.com/balenablocks/hostname
  hostname:
    build: hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: homeassistant

  # hass-configurator:
  #   image: "causticlab/hass-configurator-docker:latest"
  #   restart: always
  #   ports:
  #     - "3218:3218"
  #   volumes:
  #     - 'config:/hass-config'
  #   environment:
  #     - HC_BASEPATH=/hass-config
